import { Draggable } from '@/components/draggable'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import '../styles/globals.css'

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('font-light tracking-wider', lato.className)}>
        <Draggable>{children}</Draggable>
      </body>
    </html>
  )
}
