import type { Metadata } from 'next'

import './globals.css'

import { fontHeading } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen font-sans antialiased',
          GeistSans.variable,
          GeistMono.variable,
          fontHeading.variable,
        )}
      >
        {children}
      </body>
    </html>
  )
}
